webtalk_init -webtalk_dir D:/Repository/ai-chip-starter/vivado/vivado.sim/sim_1/behav/xsim/xsim.dir/axis_systolic_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Oct  7 15:09:53 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1d61edfb-ff95-4b06-9a2e-d476bcaedf17" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a6b62bd44738420e87facf8d3cd7a1eb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i9-13900KF" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2995 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "68.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "10396_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3366884370 -regid "" -xml D:/Repository/ai-chip-starter/vivado/vivado.sim/sim_1/behav/xsim/xsim.dir/axis_systolic_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Repository/ai-chip-starter/vivado/vivado.sim/sim_1/behav/xsim/xsim.dir/axis_systolic_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Repository/ai-chip-starter/vivado/vivado.sim/sim_1/behav/xsim/xsim.dir/axis_systolic_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
